version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: poke-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pokedex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: poke-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
